production:
    DATABASE_URL: ENC[AES256_GCM,data:TCwivOexrwfxmtOmomDPbSE2W6I7VljnryNmnJDTSkVfNd7trLlSwCigS85HjK7LwAMt7HoQrirrZCEc24w=,iv:unc/lthGV1be0eJF5TsCfrwYGphGzcloGYGUMks111Y=,tag:yaR+IKbMXrU6fi7Cmqep2Q==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:5bSz40j8UC6DFu46VaGqRAnRPNCbq9sDMzUBGAro/dIcgz0lASwexGEy,iv:ItRQjW2/aX4Bg86rqtlAFpajp8fvUIVXindXipp8ADg=,tag:5PpivOcWcycWuuBAHHsuvw==,type:str]
    API_KEY: ENC[AES256_GCM,data:oV5AUEoz+nISqyWyNmshuhI=,iv:YVNn8xPbP+Ok6KUtfNZyqGv4WqGtSk78sN78rr0b4DU=,tag:cSkkipc4ovNnPLX7O7P3KQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age120mpe2t20uqelfzknmhtzyz29dvl0rc3udv3vx0gy4jwtlymeazsuy5qlh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYklhQ1lCc0JEY1N2RWlI
            eGFnaU15TU4zR0c4ckFCUDlkYWV5R1kwQjA0CjN1OUF0N1NVNDJGL0FXYnh6UWhu
            Sm5IbVZ6RHdLd2dabWFMTDRSb0crSzAKLS0tIEk0ZW9Xbi96a281TXRTTTU3RTVX
            TWpQN3VSUzRYTkM2SHdqZTNuQ09leFEKYnEgocX1vEVCAE0jJG0cyEJnaDUHMBI2
            i6qaWktPx5jnfI+15+7Gn/8V/Zt90ur4IZD8sUGiO562pYas8OXnrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T07:55:26Z"
    mac: ENC[AES256_GCM,data:ub6Cg96V8IBAucwbddHyPhwTrrtER+oiuiSAEe5UtVWv2JpWmZ6jengKReZBHkRrni0Pey32yN96nxRLRO8GosTC2gpmTpQfw8Nxmdk6uv6ezibipgE5ju/uFE1tHQns4rXrhnhejJmCumOP8SbiJemcAWU4yN/IjYQUr/Nl8bw=,iv:Gp2+lS0l5P1KBtwkfKfo29KiNfcG2fx9fBYLgtlGlLA=,tag:+KiqydmoyHz7SuzOpVZEjA==,type:str]
    pgp: []
    encrypted_regex: ^(DATABASE_URL|JWT_SECRET|API_KEY)$
    version: 3.9.0
